use_frameworks!

platform :ios, '8.0'

target 'router_project_Example' do
  pod 'router_project', :path => '../'

  target 'router_project_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
